
trigger:
- master

pool:
  vmImage: 'windows-latest'

# ARM TTK test cases
steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: RunARMTTKTests@1
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)\'
    resultLocation: '$(System.DefaultWorkingDirectory)\'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)\*-armttk.xml'
  condition: always()

# Start with a minimal pipeline that you can customize to build and deploy your code.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'PAYG-DevOps(4f27b38c-ad3f-43d8-a9a3-01182e5e2f9a)'
    subscriptionId: '4f27b38c-ad3f-43d8-a9a3-01182e5e2f9a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dchaodevop'
    location: 'West US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/mobilesuitzero/template/master/mainTemplate.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/mobilesuitzero/template/master/parameters.json'
    deploymentMode: 'Complete'